# Generated by Django 5.0.1 on 2024-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncyclopediaSavedPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="saved_pages",
            fields=[
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
