# Generated by Django 5.0.1 on 2024-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encyclopedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncyclopediaSavedPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name="saved_pages",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
