# Generated by Django 5.0.1 on 2024-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encyclopedia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saved_pages",
            name="id",
        ),
        migrations.AlterField(
            model_name="saved_pages",
            name="user_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
